version: 1.0.0
seeders:
  file: ./seeders/seed1.rb
parsers:
  - page_type: home
    file: ./parsers/home.rb
  - page_type: status200
    file: ./parsers/status200.rb
  - page_type: /status*/i
    file: ./parsers/status200.rb