version: 0.0.1
seeder:
  file: ./seeders/seed.rb
  disabled: false
parsers:
  - page_type: default
    file: ./parsers/default.rb
  - page_type: home
    file: ./parsers/home.rb
    disabled: true
  - page_type: status200
    file: ./parsers/status200.rb
  - page_type: (?i)StaTus\d*
    regexp: true
    file: ./parsers/status200.rb